// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfX1Y-mXsIsIKqa3Crh8F1n9Ds-rcivWg',
    appId: '1:402435920861:web:6ae85a579a286b779edc34',
    messagingSenderId: '402435920861',
    projectId: 'amulx-d8abd',
    authDomain: 'amulx-d8abd.firebaseapp.com',
    storageBucket: 'amulx-d8abd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfbF6KGGkbHz6nAjRxToEaDXaYWguWfqA',
    appId: '1:402435920861:android:6c16e77bda182cbf9edc34',
    messagingSenderId: '402435920861',
    projectId: 'amulx-d8abd',
    storageBucket: 'amulx-d8abd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUxMKlGIU2WHzYh1Ed7hHnuvVfv9r_AKA',
    appId: '1:402435920861:ios:3cec9c3fb29a1ef09edc34',
    messagingSenderId: '402435920861',
    projectId: 'amulx-d8abd',
    storageBucket: 'amulx-d8abd.appspot.com',
    iosBundleId: 'com.example.amulx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUxMKlGIU2WHzYh1Ed7hHnuvVfv9r_AKA',
    appId: '1:402435920861:ios:3cec9c3fb29a1ef09edc34',
    messagingSenderId: '402435920861',
    projectId: 'amulx-d8abd',
    storageBucket: 'amulx-d8abd.appspot.com',
    iosBundleId: 'com.example.amulx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfX1Y-mXsIsIKqa3Crh8F1n9Ds-rcivWg',
    appId: '1:402435920861:web:6927d0697eb847ef9edc34',
    messagingSenderId: '402435920861',
    projectId: 'amulx-d8abd',
    authDomain: 'amulx-d8abd.firebaseapp.com',
    storageBucket: 'amulx-d8abd.appspot.com',
  );
}
